default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mOd4proJ@23
  host: localhost

development:
  <<: *default
  database: ai_chatbot_development

test:
  <<: *default
  database: ai_chatbot_test

production:
  <<: *default
  database: ai_chatbot_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
